### ISSUE TITLE
running speed

### ISSUE THREAD

**Issue by ruikangPeng** [ChatAFLndss/ChatAFL#1]
Hi, author；
I ran ChatAFL according to your guidance document, but I found that the speed of obtaining experimental results was relatively slow. Is this the same as when you ran the experiment?

**Comment by ChatAFLndss** [comment]
Hi @ruikangPeng ,

Yes, the execution time can vary for some subjects, like Kamailio, due to subject specific requirements such as state cleanup and proper termination. This is related to how we collect code coverage data. After the fuzzing campaign completes, all seeds are replayed on the coverage instrumented version, and coverage metrics are then obtained using the `gcov` program.

**Comment by ruikangPeng** [comment]
@ChatAFLndss Thank you for your reply. 
I have learned a lot from your research, especially the one click script execution experiment, which is particularly eye-catching. I hope to have more communication with you in the field of protocol fuzzing.

**Comment by ChatAFLndss** [comment]
@ruikangPeng Thank you. Happy to discuss with you more!

**Comment by moyiun09** [comment]
Hi @ruikangPeng This OPENAI_API_KEY is provided in the appendix of the article. I did not find the corresponding key. Did you use the key you applied for?

**Comment by ChatAFLndss** [comment]
@moyiun09 Sorry, but we do not make the OpenAI key available to the public. It is only provided to reviewers in the NDSS artifact evaluation

**Comment by moyiun09** [comment]
@ChatAFLndss
Thank you for your reply.
Now I understand. Although I have not been able to reproduce this project,
it is a good idea.

ChatAFLndss ***@***.***> 于2023年10月30日周一 18:54写道：
